import type { Agent, AgentsData, Workflow } from './types'

// This file is imported at build time by Next.js Server Components.
// agents.json is generated by `npm run scan` before `next build`.
let data: AgentsData | null = null

function loadData(): AgentsData {
  if (data) return data
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    data = require('../data/agents.json') as AgentsData
  } catch {
    // Return empty data if not yet generated
    data = {
      generatedAt: new Date().toISOString(),
      agents: [],
      workflows: [],
    }
  }
  return data
}

export function getAllAgents(): Agent[] {
  return loadData().agents
}

export function getAgentBySlug(slug: string): Agent | undefined {
  return loadData().agents.find((a) => a.id === slug)
}

export function getAllWorkflows(): Workflow[] {
  return loadData().workflows
}

export function getWorkflowById(id: string): Workflow | undefined {
  return loadData().workflows.find((w) => w.id === id)
}

export function getGeneratedAt(): string {
  return loadData().generatedAt
}

export function getDashboardStats() {
  const { agents, workflows } = loadData()
  const totalTokens = agents.reduce((sum, a) => sum + a.compensation.totalTokens, 0)
  const totalCost = agents.reduce((sum, a) => sum + a.compensation.estimatedCostUSD, 0)
  const models = Array.from(new Set(agents.map((a) => a.model)))
  return {
    totalAgents: agents.length,
    totalWorkflows: workflows.length,
    totalTokens,
    totalCostUSD: Math.round(totalCost * 100) / 100,
    uniqueModels: models.length,
    models,
  }
}
